### ISSUE TITLE
Deploy to PyPI, Docker, etc

### ISSUE THREAD

**Issue by pauldraper** [renanvieira/phoenix-letter#11]
I'd like to have an easier way to install than cloning VCS repo and running build tools.

**Comment by renanvieira** [comment]
It's already on PyPI: https://pypi.org/project/phoenix-letter

**Comment by pauldraper** [comment]
Thanks! I had assumed it wasn't because it's not in README.

**Comment by renanvieira** [comment]
@pauldraper Yeah, that makes sense. I only realised that there were no link or mention to PyPI in the readme after your issue. 
I've updated the readme to avoid this confusion in the future. So, thank you. :)
